### ISSUE TITLE
Clipping Type Instabilities

### ISSUE THREAD

**Issue by skygering** [asinghvi17/GeometryOps.jl#73]
I don't know if #69 takes care of this but, I am still seeing type instability, both from `tuples`, and also from the `target`.

<img width="789" alt="Screenshot 2024-03-05 at 5 03 09 PM" src="https://github.com/asinghvi17/GeometryOps.jl/assets/60117338/873524f8-1db0-4920-8582-59e9bc802b33">
<img width="901" alt="Screenshot 2024-03-05 at 7 09 05 PM" src="https://github.com/asinghvi17/GeometryOps.jl/assets/60117338/f61d73f5-a5a6-4d41-a2e6-cd58abb472dc">
<img width="1034" alt="Screenshot 2024-03-05 at 12 48 50 PM" src="https://github.com/asinghvi17/GeometryOps.jl/assets/60117338/9c0c7257-4a80-45c3-aee7-2016b937d60f">

To reproduce use:
```julia
import GeoInterface as GI
import GeometryOps as GO
using ProfileView
using Cthulhu

p25 = GI.Polygon([[(0.0, 0.0), (5.0, 0.0), (5.0, 8.0), (0.0, 8.0), (0.0, 0.0)],
    [(4.0, 0.5), (4.5, 0.5), (4.5, 3.5), (4.0, 3.5), (4.0, 0.5)],
    [(2.0, 4.0), (4.0, 4.0), (4.0, 6.0), (2.0, 6.0), (2.0, 4.0)]])
p26 = GI.Polygon([
    [(3.0, 1.0), (8.0, 1.0), (8.0, 7.0), (3.0, 7.0), (3.0, 5.0), (6.0, 5.0), (6.0, 3.0), (3.0, 3.0), (3.0, 1.0)],
    [(3.5, 5.5), (6.0, 5.5), (6.0, 6.5), (3.5, 6.5), (3.5, 5.5)],
    [(5.5, 1.5), (5.5, 2.5), (3.5, 2.5), (3.5, 1.5), (5.5, 1.5)]])

GO.intersection(p25, p26; target = GI.PolygonTrait)

f(n, p1, p2) = for _ in 1:n GO.intersection(p1, p2; target = GI.PolygonTrait) end
ProfileView.@profview f(10000, p25, p26)
```

The profile won't look just like the one above until #72 is merged, but the type unstable bar will still be there.

**Comment by asinghvi17** [comment]
Yeah I see it as well - there's a type instability in `GO.tuples`

**Comment by rafaqz** [comment]
Yeah its not perfect, but thats only a small fraction of runtime? 

I think the compiler cant see right through the next level of nesting to know the return type. But the next level is where all the work is so its not the worst thing.
