### ISSUE TITLE
Planned feature: barycentric coordinates on arbitrary polygons (without holes)

### ISSUE THREAD

**Issue by asinghvi17** [asinghvi17/GeometryOps.jl#9]
I'm in the process of writing a mesh rasterizer for CairoMakie which can rasterize quads on the CPU, and uses true quads instead of splitting into triangles.  A part of this is obtaining barycentric coordinates for interpolation.

Barycentric coordinates are basically just a decomposition from Cartesian space into a (possibly degenerate) space of dimension _N_ (where _N_ is the number of vertices of the polygon), and the values are the relative nearness of the point to each of the vertices.  Barycentric coordinates always sum to 1.

Creating this software rasterizer would allow us to really fiddle with meshes and do some pretty interesting stuff, like custom color mixing, working in LAB instead of RGB space, etc.  It also allows us to smoothly (and correctly) interpolate values across an arbitrary polygon.  See this example from CGAL:

![](https://doc.cgal.org/latest/Barycentric_coordinates_2/terrain_interpolation.png)

There are some pretty useful resources here:

https://doc.cgal.org/latest/Barycentric_coordinates_2/index.html

[Wachspress + mean value coords.pdf](https://github.com/asinghvi17/GeometryOps.jl/files/11522183/Wachspress.%2B.mean.value.coords.pdf)
[How to compute mean value coordinates.pdf](https://github.com/asinghvi17/GeometryOps.jl/files/11522190/How.to.compute.mean.value.coordinates.pdf)
[Bloomenthal2022Barycentric.pdf](https://github.com/asinghvi17/GeometryOps.jl/files/11522185/Bloomenthal2022Barycentric.pdf)

I'll probably have a decently working implementation of this up in a week or so.

**Comment by asinghvi17** [comment]
For reference, this is Makie's current output (interpolation via triangulation):
CairoMakie:
![download-1](https://github.com/asinghvi17/GeometryOps.jl/assets/32143268/bc554f3c-a341-43c9-a38c-5bde3ba5a228)
GLMakie:
<img width="512" alt="Screenshot 2023-05-20 at 7 28 45 AM" src="https://github.com/asinghvi17/GeometryOps.jl/assets/32143268/da1b080a-66d7-49b3-8178-59bf6aa0a339">

**Comment by asinghvi17** [comment]
Had some success with mean value coordinates:

![download-5](https://github.com/asinghvi17/GeometryOps.jl/assets/32143268/938ac47c-a716-4ff8-8059-4e04ed74b3ac)

will try to implement at least Wachspress and harmonic with ChatGPT's help (it gave me a lot of bugs in the code though :().

**Comment by DanielVandH** [comment]
@asinghvi17 I recently released a package with some similar coordinates https://github.com/DanielVandH/NaturalNeighbours.jl if you also want to see how they perform. `Sibson(1)` might look good.

**Comment by asinghvi17** [comment]
Thanks!  Will definitely try that out and see what it looks like.

**Comment by DanielVandH** [comment]
Ahh, didn't think about `Float32` - my mistake. This is actually a DelaunayTriangulation.jl issue - ExactPredicates.jl only works for Float64 unfortunately. I will patch this for you @asinghvi17, converting everything into Float64.

**Comment by DanielVandH** [comment]
@asinghvi17 It should be fixed now on NaturalNeighbours.jl v1.0.2 (+ DelaunayTriangulation 0.7.2), if you want to try again.

**Comment by asinghvi17** [comment]
Thanks!  Will try it out.  That might be an interesting addition to either the `tricontour` recipe or TopoPlots.jl!

Solved by #10

**Comment by asinghvi17** [comment]
A bit late - I never did end up incorporating NaturalNeighbours.jl into this.  It could conceivably be done as a package extension into the interface but I was never really into that.  

For reference, this is all the NaturalNeighbours.jl methods (+ our own mean value method) 

![rendering methods](https://github.com/asinghvi17/GeometryOps.jl/assets/32143268/76d58ec7-89dd-43bd-ab1c-0f037b2a6f7a)

NaturalNeighbors uses a pre-constructed triangulation object, as do a couple of other similar interpolation methods.
