### ISSUE TITLE
Handle GeoInterface.jl compatible tables

### ISSUE THREAD

**Issue by rafaqz** [asinghvi17/GeometryOps.jl#90]
Probably we should allow GeoInterface.jl compatible tables in `apply` ? (Tables.jl compatible with a `:geometry` column or something else specified by `GeoInterface.geometrycolumns`).

But probably it should also return a Table? to keep the "returns a similar object" pattern.

Could we default to using a `DataFrame` and put DataFrames.jl part in an extension?

This means `applyreduce` could work with just Tables.jl but `apply` would need DataFrames.jl

**Comment by asinghvi17** [comment]
Sounds like a plan - one could also do the same for `applyreduce`.

Doesn't apply work correctly on FeatureCollections already?

**Comment by asinghvi17** [comment]
Apply works on GeoJSON feature collections but returns an object which is not compatible with the Tables.jl interface.  Shapefile tables are not supported yet, unfortunately.

**Comment by asinghvi17** [comment]
Suppose a table has geometries of type `Point`, `Polygon` and `MultiPolygon`.  Now, if someone calls `apply` on it targeting polygon types, do we skip the point, or throw an error?  Does the reconstructed table contain the point (I want to say no)?
